Pytorch Basics

In [1]:
import torch

In [2]:
torch.rand(2,2)

tensor([[0.2719, 0.3823],
        [0.4341, 0.9324]])

In [3]:
x=torch.empty(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
x=torch.tensor([2.4,4,4], dtype=int)
x

tensor([2, 4, 4])

In [6]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=x+y 
z=torch.add(x,y)
print(z)

tensor([[0.8503, 0.9911],
        [0.5410, 0.3806]])
tensor([[0.3856, 0.1760],
        [0.4647, 0.1287]])
tensor([[1.2359, 1.1671],
        [1.0057, 0.5093]])


In [7]:
x=torch.rand(5,3)
print(x)
print(x[0,:])
print(x[:,1])

tensor([[0.7981, 0.6565, 0.7489],
        [0.6865, 0.1663, 0.0496],
        [0.5046, 0.1227, 0.9312],
        [0.8699, 0.5369, 0.1093],
        [0.8324, 0.1151, 0.7940]])
tensor([0.7981, 0.6565, 0.7489])
tensor([0.6565, 0.1663, 0.1227, 0.5369, 0.1151])


Reshape

In [8]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)

tensor([[0.4866, 0.3595, 0.3155, 0.0087],
        [0.8464, 0.1496, 0.6226, 0.6612],
        [0.1291, 0.7187, 0.3954, 0.8920],
        [0.1619, 0.1811, 0.1403, 0.9529]])
tensor([0.4866, 0.3595, 0.3155, 0.0087, 0.8464, 0.1496, 0.6226, 0.6612, 0.1291,
        0.7187, 0.3954, 0.8920, 0.1619, 0.1811, 0.1403, 0.9529])


In [9]:
y=x.view(-1,8)
print(y)

tensor([[0.4866, 0.3595, 0.3155, 0.0087, 0.8464, 0.1496, 0.6226, 0.6612],
        [0.1291, 0.7187, 0.3954, 0.8920, 0.1619, 0.1811, 0.1403, 0.9529]])


Conversion : Numpy to tensor and Vice Versa

In [10]:
import numpy as np

In [11]:
a=torch.ones(5)
print(a)

b=a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [12]:
a.add_(2) #inplace addition
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [13]:
a=np.ones(5)
print(a)

b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [14]:
a+=1
print(a)

print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Check CUDA is installed or not

In [15]:
if torch.cuda.is_available():
    device=torch.device("cuda")
    x=torch.ones(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    z=z.to("cpu")
    

For Gradient

In [16]:
x=torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [17]:
x=torch.rand(5, requires_grad=True)
print(x)

tensor([0.1482, 0.7858, 0.3744, 0.4641, 0.9390], requires_grad=True)


In [18]:
y=x+2
print(y)

tensor([2.1482, 2.7858, 2.3744, 2.4641, 2.9390], grad_fn=<AddBackward0>)


In [19]:
z=y*y*2
print(z)

tensor([ 9.2298, 15.5214, 11.2760, 12.1437, 17.2760], grad_fn=<MulBackward0>)


In [20]:
z=z.mean()
print(z)

tensor(13.0894, grad_fn=<MeanBackward0>)


In [21]:
z.backward() #dz/dx
print(x.grad)

tensor([1.7186, 2.2286, 1.8996, 1.9713, 2.3512])


Conversion : uint8 to float32

In [ ]:
uint8_tensor=torch.tensor([0,22,44], dtype=torch.uint8)
float32_tensor=torch.tensor(uint8_tensor, dtype=torch.float32)
print(uint8_tensor)
print(float32_tensor)

tensor([ 0, 22, 44], dtype=torch.uint8)
torch.float32


C:\Users\anant\AppData\Local\Temp\ipykernel_18344\1867669023.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float32_tensor=torch.tensor(uint8_tensor, dtype=torch.float32)


In [30]:
float32_tensor=uint8_tensor.to(torch.float32)
print(float32_tensor)

tensor([ 0., 22., 44.])
